# Generated by Django 5.1.3 on 2025-01-14 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_videopost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='section',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.navbaritem'),
        ),
    ]
