# Generated by Django 5.1.3 on 2025-01-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_videopost_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='youtube_embed_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
