# Generated by Django 5.1.3 on 2025-01-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_videopost_youtube_embed_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videopost',
            old_name='youtube_embed_link',
            new_name='youtube_link',
        ),
    ]
